### PR TITLE
Separate dependencies with devDependencies

### PR DESCRIPTION
**Pull request by rpunkfu**

### CODE REVIEW

**Comment by jodelamo** [comment]
Does this play well with Heroku?

**Comment by rpunkfu** [comment]
Hmm.. I don't know, will check that later ;) But I think you don't want those in Heroku anyway, build should contain already transpiled, bundled code?

**Comment by jaredpalmer** [comment]
@jlowgren I believe there is a way to tell heroku to download devDependencies on build by possibly setting `NODE_ENV` to development in `app.json`. You would then need to set `NODE_ENV` to production in `Procfile`'s `web` service. However, I usually just keep everything in dependencies. 

@oskarcieslik the benefit of building the code on deploy is that you can use Heroku's GitHub flow for review apps and pipelines while keeping bundled code out of git.

**Comment by rpunkfu** [comment]
@jaredpalmer, cool ;) I am always building app on travis (or something else) and then it pushes this bundled code to Heroku, but I will check out Heroku's Github flow. So what do you think, is it a good idea to move those dependencies to devDependencies?

**Comment by jaredpalmer** [comment]
this is @mjackson's setup, so not my decision. personally, i would keep them where they are and not mess with deployment.

**Comment by mjackson** [comment]
Thanks for commenting here, @jaredpalmer. You nailed it.

**Pull request closed without merging**
